### ISSUE TITLE
Object parsing can panic!() on bad input

### ISSUE THREAD

**Issue by reinerp** [rspencer01/microjson#5]
Object parsing calls assert!() (https://github.com/rspencer01/microjson/blob/7e3d84a35471efdfee5e32597239c7b2a5af5611/src/lib.rs#L422) and unwrap() where it expects the input buffer to be valid JSON. For use cases with potentially bad input, this is a dealbreaker. I would prefer to have a (potentially even more manual) API that exposes parse failure rather than panicking on it.

**Comment by rspencer01** [comment]
Changing the API to return an iterator of `Result`s here and [here](https://github.com/rspencer01/microjson/blob/master/src/lib.rs#L486C38-L488) will also resolve the `unwrap` in the `EscapedStringIterator`. We should probably demonstrate how to neatly turn it into a `Result<String, ...>` with `.collect` in the documentation.

**Comment by bglw** [comment]
NB: This would also panic on empty objects `{}` as there was no initial `"` to match. 

Using the latest git rev this is fixed 🎉 Looking forward to a release 🙂
