### ISSUE TITLE
std float parsing brings in a lot of code

### ISSUE THREAD

**Issue by reinerp** [rspencer01/microjson#6]
I wrote a code-size benchmark for parsing some JSON, and compared to miniserde. My benchmark involved parsing an array of objects with string, integer, and float keys. I looked at the generated code size in wasm. I did this in both microjson and mini_serde.

In this benchmark, microjson comes in at 24380 bytes, whereas miniserde comes in 11470 bytes. The difference is explained by float parsing: microjson uses std, whereas miniserde rolls its own, which is accurate for small numbers but may be incorrectly rounded (by 1 ULP) for some numbers, but has the advantage of generating much less code. https://github.com/dtolnay/miniserde/blob/99c643db2b2a08678943289626ba0653617228c2/src/json/de.rs#L466.

In my benchmark, if I remove the float parsing but keep the rest, microjson size comes down to 6111 bytes.

Consider using minimal_lexical with features=["compact"], or consider using just the fast-but-slightly-inaccurate algorithm from miniserde.

**Comment by rspencer01** [comment]
`microjson` is not primarily intended to compile down to the smallest possible codesize. However, this is a worthy secondary goal and I would be interested in looking at minimising the output slightly. I agree that `std` is too heavy a dependency for something like parsing floats.
